### ISSUE TITLE
Założenia projektowe

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#1]
Pierwszy krok - musimy ustalić, co konkretnie ma robić nasz system i w jaki sposób. Zostawiajcie sugestie w komentarzach, a po ustaleniu konkretnej wersji będziemy edytować ten wpis.

Ekrany są rozpisane w #12 

Technologie:
- baza danych - np MySQL, nalegałbym na umieszczenie jej na jakimś darmowym zdalnym serwerze, aby każdy z nas miał do niej dostęp, do tych samych danych. Dane byśmy wpisali z palca, bo nie potrzebujemy ich jakoś dużo, do tego muszą być dostosowane do struktury, jaką zaprojektujemy
- moduł `backend` - odpowiedzialny za połączenie z bazą danych - jako że taką tematykę będziemy mieć na przedmiocie z .NET, sugeruję skorzystanie właśnie z tej technologii. Alternatywy to Spring Boot (Java) albo node.js
- moduł `frontend` - strona internetowa, oczywiście JavaScript, CSS itp. Możemy użyć Reacta, dzięki któremu możemy stworzyć szybciej ładnie wyglądającą stronkę (przykłady komponentów: https://material-ui.com/, https://www.primefaces.org/primereact/#/). Mogę Wam kiedyś pokazać, jak się to robi w React, jeśli byście chcieli w tym pisać. Alternatywa to tradycyjny JS, lecz wtedy praca by trwała dłużej, no i nie zrobimy takich fajnych fajerwerków.
- komunikacja między frontendem a backendem: REST API jest fajne i wygodne, w JS nie potrzeba do tego żadnej biblioteki, natomiast dla .NET jest to w ASP.NET
- moduł aplikacji mobilnej - opakowalibyśmy frontend w ramkę korzystając z jakiegoś narzędzia, dzięki temu nie musielibyśmy robić tego osobno. Trzeba będzie też jakoś zaimplementować obsługę kodów QR i kreskowych, ale może będzie się dało to obsłużyć we frontendzie, nie wiem.
- chmura - fajnie by było, żeby nasza apka była gdzieś odpalona, dostępna w necie tak po prostu, w jakimś trybie demonstacyjnym. Ponoć można umieszczać takie projekty na Heroku, myślę, że warto to rozważyć.

**Comment by kamil-blonski** [comment]
Skoro ma to być aplikacja internetowa to oprócz formularza do logowania można by dodać formularz rejestracyjny. Jak już wszystko skończymy to możemy pomyśleć o jakiejś stronie domowej gdzie będą zrzuty, opis funkcji itp., żeby łatwiej "sprzedać" projekt przy oddawaniu.

Opisze może jak ja sobie taki system wyobrażam na podstawie tego co oglądałem i później ewentualnie można z tego powyciągać albo powyrzucać funkcjonalności (o ile w ogóle dobrze to wszystko zrozumiałem).

Po zarejestrowaniu się pokazuje się okno z możliwością dodania lokalizacji i spis lokalizacji już utworzonych. Każda lokalizacja powinna zawierać spis pomieszczeń i ewentualnie spis pracowników. Dr Sroczyński na pewno mówił, że urządzenie ma mieć przypisaną osobę i sale, w której np. pracuje.
 To też się przyda potem przy dodawaniu sprzętu, zamiast wpisywać pokoje i nazwiska "z palca" można zrobić zamkniętą listę wyboru. Oczywiście takie spisy osób/pokoi wiązałyby się z możliwością ich edycji/dodawania/usuwania, szczególnie ludzi.

W zadaniu jest napisane, że mamy prowadzić ewidencje sprzętu komputerowego i oprogramowania. Tutaj zastanawiałem się czy nie rozbić tego na dwie opcje w naszym systemie. Niezależnie od tego jakie to będzie oprogramowanie to wydaje mi się, że przypisywać je będziemy do całej, jednej stacji roboczej. Więc jak będą dodane np. komputery w danym pokoju czy budynku to potem przy dodawaniu licencji można znowu zrobić coś w rodzaju zamkniętej listy żeby nie wprowadzać nazw stacji z klawiatury. Jeśli chodzi o dodawanie sprzętu do spisu to zależy od tego jakie informacje będziemy chcieli umieścić, więc tu jeszcze niczego nie proponuje. Na pewno będzie trzeba uwzględnić to o czym mówił Sroczyński - w przypadku np. kupna gotowego laptopa można po prostu wpisać jego nazwę albo rozbić opis takiego laptopa na wszystkie podzespoły. W przypadku licencji no to oczywiście nazwa oprogramowania, okres, typ licencji, na jaką stacje i dla jakiego użytkownika.
Dodawanie takiego "pierwszego spisu", na podstawie którego będzie później wykonywana inwentaryzacja to pierwszy krok. Bo jakby nie wiem czy do końca też dobrze to rozumiem. "Wydruk kart inwentarzowych", chodzi o:

- Wygenerowanie raportu (spisu) listy urządzeń i licencji w danej lokalizacji lub dla danego użytkownika
czy
- Dodanie nowej listy sprzętu i licencji w danej lokalizacji i później wygenerowanie raportu, który będzie wykazywał różnice w stanie początkowym i obecnym (na takiej zasadzie działają te programy, o których czytałem).

Opcja 1 oszczędziłaby nam masę pracy, więc dajcie znać jak to rozumiecie. I w sumie od wyboru odpowiedniej kropki zależy to jak ta aplikacja będzie wyglądać dalej więc na razie się wstrzymam.

**Comment by bartlomiej-szlachta** [comment]
Formularz rejestracyjny - na pewno pozwolimy użytkownikom na samowolną rejestrację? Chyba zwykle w takich systemach to admin tworzy konta wszystkim użytkownikom.

Strona główna - dobry pomysł, zdecydowanie do zostawienia na koniec.

W trzecim akapicie domyślam się, że przez 'sala' i 'pokój' masz na myśli lokalizację. Tutaj się zgadzam z ideą, o ile dobrze się domyśliłem.

Co do ostatniego dylematu - dążmy do tego, żeby to rozumieć jako tą pierwszą, prostszą opcję xD Oczywiście wszystko skonsultuję dzisiaj z 'klientem'.

**Comment by kamil-rusin** [comment]
Funkcjonalność:
- logowanie musi być - bezpieczeństwo danych
- konto użytkowników zakładane z góry przez admina, bo wszyscy nie mogą mieć dowolnego dostępu do tych danych
- hm... może widok kafelek - główne menu, tam możemy kliknąć w "Mój sprzęt"?, gdzie będziei lista rzeczy za które jesteśmy odpowiedzialni? albo lista sal
- wydruk informacji z ekranu dodane do formularza

Technologie:
- baza danych - też byłbym za MySQL i zdalnym serwerze, swoją drogą fajny jest Firebase
- backend - .NET fajny, ewentualnie jestem chętny do nauki alternatyw
- frontend - jestem chętny na naukę Reacta
- apka mobilna - obsługa kodu QR jest dosyć spoko, kodujesz coś do np. JSON'a i potem z kamerki łatwo idzie odczytać. Robiłem tak z Mixerem w projekcie dla Urygi
- chmura - śmiało można testować, jednak dopiero gdy ustalimy i zrobimy już całą strukturę


Formularz rejestracyjny:
- można zrobić formularz i admin musi to akceptować, bądź lepiej byłoby, gdyby admin miał możliwość tworzenia kont z góry jak to było na Systemach Operacyjnych

Strona główna:
- tak jak wspominałem, bardzo fajne, bo stamtąd można przekierować użytkownika do czego tylko będzie chciał

Zestaw komputerowy:
- możemy zrobić też tak, że jak ktoś chce dodać zestaw to istnieje możliwość rozgałęzienia, np. właśnie zestawu i jak będzie taka potrzeba to ręcznie doda sobie klikając w "coś" przy zestawie. Wyskoczy nowe okienko z dodaniem komponentów tego zestawu. Nie wiem czy zrozumieliście co mam na myśli :D 

Wydruk kart:
- miejmy nadzieję, na pierwszą kropkę bo dużo mniej pracy, ale skoro mamy 'samograja' to może nam kazać zrobić drugą :/

**Comment by bartlomiej-szlachta** [comment]
Zaktualizowałem koncept, starałem się najdokładniej jak się da. Natomiast na pewno coś przeoczyłem, dlatego sprawdźcie to i dajcie znać, co Wy na to. Jak wszyscy razem ustalimy koncept, to przeniosę tą finalną wersję do jakiegoś innego pliku, a Issue zamknę.

Utworzyłem też kilka pierwszych zadań, jak ktoś jest chętny je zrobić, to śmiało można sobie takie przypisać ('assign yourself') :wink:

**Comment by oliwiabrozek** [comment]
- baza - też jestem za MySQLem
- backend - jak będziemy mieć coś takiego na labach z .NETa to byłby plus, ale Spring Boot jest o tyle super, że bardzo łatwo się go używa 😃 
- front - na pewno warto użyć jakiegoś frameworka
- karta inwentarzowa - jestem na 99% pewna, że chodzi o rodzaj raportu 😜 

sorki za opóźnienie, już sobie włączyłam powiadomienia 😅

**Comment by bartlomiej-szlachta** [comment]
Postanowione:
- przez przynależność rozumiemy salę / pokój / osobę, wszystkie tak samo
- można osobie przypisywać sprzęty, niezależnie od lokalizacji
- nie wprowadzamy opiekunów sal, zamiast tego dla każdej sali można wyświetlić listę osób, do których należą sprzęty z tej sali <- nieaktualne?
- numer inwentarzowy dla każdego fragmentu sprzętu / dla kompletu
- możliwość dołożenia nowego fragmentu sprzętu z własnym numerem inwentarzowym
- zapisywanie daty zakupu, data montażu, data zakończenia, daty gwarancji - od kiedy do kiedy jest w tym miejscu
- fragment sprzętu może być przenoszony między komputerami - historia zmian
- urządzenia przenośne nie przypisywać do sal, tylko do osób
- przypisywanie sprzętu albo do sali, albo do osoby - albo to, albo to
- 
- karty inwentarzowe:
  - historia dla przynależności
  - aktualny stan dla przynależności
  - historia dla sprzętu
  - auktualny stan dla sprzętu
