### ISSUE TITLE
Przygotowanie prezentacji

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#10]
Na pierwszy tydzień listopada mamy do zrobienia prezentację (szczegóły w `docs/*.pdf`). Potrzebujemy prezentacji online, którą wszyscy byśmy mogli edytować, a która w finalnej wersji by była przesłana do klienta.

**Comment by kamil-rusin** [comment]
Inicjalizacja prezki:
https://docs.google.com/presentation/d/14qh80aPmTCao2ZK5S9DxJBLvwF7rxgcU-MHZeTFXsS8/edit?usp=sharing

**Comment by bartlomiej-szlachta** [comment]
Teraz tutaj byśmy dyskutowali na temat wszystkiego, co dotyczy prezentacji. Wcześniejsza konwersacja dotycząca przykładowych kodów projektów znajduje się w #5.

**Comment by kamil-rusin** [comment]
Czy w prezentacji mam dodać dlaczego zdecydowaliśmy się na apkę w React Native, a nie na konwertery itp. itd.?
