### ISSUE TITLE
Wystawienie aplikacji backendowej na serwer

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#102]
Nasza aplikacja serwerowa musi się znaleźć na serwerze, żeby łatwiej dało się do niej dostać. Dzięki temu będziemy w stanie testować aplikację mobilną. Poszukam dostępnych opcji (np Heroku, albo jakieś inne). Tam apka będzie chodzić cały czas i odbierać żądania. Dodatkowo w kodzie ustawię globalnie wysyłanie połączeń API na tą naszą aplikację na serwerze.

**Comment by kamil-blonski** [comment]
https://dry-wildwood-77221.herokuapp.com

**Comment by bartlomiej-szlachta** [comment]
Ja się zajmę uwzględnieniem tego na frontendzie
