### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/co-gdzie-kiedy#105]
Jeżeli emulator nie uruchamia się sam to trzeba zrobić to ręcznie (inaczej poleci błąd)  z android studio. W dowolnym projekcie trzeba uruchomić AVD Manager i uruchomić urządzenie bez żadnej niepotrzebnej aplikacji.
Zmiany, które dokonałem u siebie dodatkowo żeby emulator działał (poza rzeczami z instrukcji na dzień dzisiejszy):

- Instalacja metro serwera. W _co-gdzie-kiedy\frontend\\_ uruchomić polecenie:
`npm install --save-dev metro metro-core`

- Uruchomienie frontendu ( _co-gdzie-kiedy\frontend\android\\_) w android studio i poczekania aż projekt się zbuduje (u mnie to trwało dłuższą chwilę). Wszystko powinno być ma zielono po zbudowaniu, jeśli nie jest to trzeba sobie naprawić wg. wskazówek z android studio.

Błąd **Unable to load script ...**, taki czerwony, wyświetlany w emulatorze przy uruchamianiu (widzieliśmy na wspólnym spotkaniu):
- Dodanie do Path folderu npm z %appdata% (wpisać w uruchom)

- Uruchomić w  _co-gdzie-kiedy\frontend\\_ komende `npm install -g react-native-cli`

- Spróbujcie sobie wykonać polecenie `react-native start` w  _co-gdzie-kiedy\frontend\\_. Jeśli poleci wam błąd _**react native start invalid regular expression ...**_ to trzeba w pliku _frontend\node_modules\metro-config\src\defaults\blacklist.js_ zamienić blok kodu (6 linii). Całe sharedBlacklist, które jest w tym pliku trzeba usunąć i wkleić to pod spodem.

```
var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```

**Comment by bartlomiej-szlachta** [comment]
Pierwszy z wymienionych sposobów to dodanie nowych zależności do projektu (`package.json`):
```
"devDependencies": {
    "metro": "^0.57.0",
    "metro-core": "^0.57.0"
  }
```

Jeśli tak robimy, to upewnijmy się, że tego nie commitujemy przy swoich feature'ach. Jeśli to rzeczywiście naprawia problem, to dodamy to raz, w osobnym commicie

**Comment by bartlomiej-szlachta** [comment]
@kamil-rusin spróbuj wykonać 5-ty punkt (`npm install -g react-native-cli`), wydaje się sensowny

**Comment by kamil-rusin** [comment]
> @kamil-rusin spróbuj wykonać 5-ty punkt (`npm install -g react-native-cli`), wydaje się sensowny

Dalej nie działa :( Coś się instalowało, ale wywala i na emulatorze i na telefonie.

**Comment by kamil-blonski** [comment]
Kamil prosił więc przy okacji wrzucę tu screen z moich ścieżek środowiskowych. Drugi screen to Path.

![80738761_2482265265347172_5198846011006517248_n](https://user-images.githubusercontent.com/33577175/71249139-cdfa2280-231c-11ea-88b0-c6a119f8ec3e.png)
![Przechwytywanie](https://user-images.githubusercontent.com/33577175/71249141-ce92b900-231c-11ea-9345-f069ee90d240.PNG)

**Comment by kamil-rusin** [comment]
Zależnośc z Metro + zmiana w pliku `blacklist`. To na 100% rozwiązanie problemu.

**Comment by bartlomiej-szlachta** [comment]
W takim razie dodam to do instrukcji, dzięki za rozpisanie tego 😎

**Comment by kamil-rusin** [comment]
Zamykamy?

**Comment by bartlomiej-szlachta** [comment]
Jeszcze nie, u @oliwiabrozek jeszcze nie działa. Jak już będzie działać, to wtedy zamkniemy to issue wraz ze #115
