### ISSUE TITLE
Testy kontrolera zestawów komputerowych

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#113]

**Comment by oliwiabrozek** [comment]
Miałam zrobić takie issue 😆🙄🤪

**Comment by kamil-blonski** [comment]
Jest gałąź osobna, większość testów jest, potem posprawdzam czy działają po zmianach i dopisze nowe jak już sie da

**Comment by bartlomiej-szlachta** [comment]
Wyprzedziłem Cię 😜
