### ISSUE TITLE
Tajemnicze zapytania o ikonę strony internetowej

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#128]
😕 

![image](https://user-images.githubusercontent.com/37980016/71768871-ce98d880-2f1a-11ea-858a-62c0ed0d5ef6.png)

**Comment by kamil-rusin** [comment]
https://stackoverflow.com/questions/9371378/warning-not-found-favicon-ico

W skrócie chyba trzeba ustawić ścieżkę do jednej ikonki dla wszystkich ekranów. Chyba tak to zrozumiałem :/
