### ISSUE TITLE
Mylący nagłówek kolumny

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#129]
Na liście software'u jest taka kolumna:

![image](https://user-images.githubusercontent.com/37980016/71769294-892ada00-2f1f-11ea-9247-6424d4803c82.png)

Rozumiem, że wartości oznaczają czas trwania w milisekundach? Jeśli tak, to trzeba zmienić tytuł tej kolumny na 'Czas trwania' oraz zaznaczyć, że tabelka ma to sformatować na czas, podając `timestamp: true` do obiektu będącego elementem tablicy `columns` w `SoftwareListContainer`. Tabelka nie wyświetli tego inaczej od razu, dopiero dorobię taką funkcjonalność

**Comment by kamil-blonski** [comment]
Wiem, że trzeba

**Comment by kamil-blonski** [comment]
Zrobione w feature-software-actions
