### ISSUE TITLE
Widok mobilny formularza software'u

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#138]
Trzeba umożliwić korzystanie z formularza w trybie mobilnym:

![image](https://user-images.githubusercontent.com/37980016/71916680-c50faa80-317e-11ea-9397-a4a704ee5622.png)

**Comment by kamil-blonski** [comment]
Zmieniłem stałe wartości na %, formularz jest widoczny na mobilkach.
