### ISSUE TITLE
Ładowanie inicjalnych danych do pól tekstowych w formularzu software

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#140]
W trybie edycji trzeba na starcie załadować dane i wpisać je w pola tekstowe

**Comment by kamil-blonski** [comment]
![image](https://user-images.githubusercontent.com/33577175/71917218-dd33f980-317f-11ea-9bae-b022ea04fe4c.png)

ładują sie

**Comment by kamil-blonski** [comment]
Dodałem niepotrzebnie ścieżki lokalne do konkretnych zapytań, jutro je usunę i będzie działać.
