### ISSUE TITLE
Drukowanie list do pdf

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#142]

**Comment by kamil-rusin** [comment]
https://github.com/christopherdro/react-native-html-to-pdf
https://blog.bam.tech/developer-news/the-tech-news

**Comment by bartlomiej-szlachta** [comment]
Obie ta biblioteka nam się nie przyda niestety - potrzebny by był html w postaci stringa. Może być ciężko znaleźć taką bibliotekę, która przekonwertuje dane z ekranu do pdf, ale jeszcze poszukam. W razie czego trzeba by to zaimplementować na backendzie i przesyłać do frontendu gotowy plik.

**Comment by bartlomiej-szlachta** [comment]
Można skorzystać z `com.itextpdf.text` (java)
