### ISSUE TITLE
Populacja bazy danych

### ISSUE THREAD

**Issue by kamil-rusin** [Samograje/co-gdzie-kiedy#148]
Z racji tego, że powoli zbliżamy się do terminu oddania projektu, wypadałoby wykonać test dla dużej ilości danych, jak również ustalić ostateczną bazę danych, na której będziemy prezentować projekt. 

Nie śpieszy się jeszcze.

**Propozycja:**
Każdy dodaje rekordy dla swojej części. Ważna jest kolejność dodawania rekordów z racji używania ich w innych formularzach:
Przynależności -> Zestawy Komputerowe -> Słownik sprzętów -> Sprzęt (dodawany do zestawów) -> Oprogramowanie(obojętnie w którym momencie)

Co uważacie?

**Comment by kamil-blonski** [comment]
3 tygodnie jeszcze więc myśle że na to można poświęcić czas w ostatnim, do tej pory sie dorobi więcej

**Comment by bartlomiej-szlachta** [comment]
Populacja - już myślałem, że chodzi o heurystyki 😄 
Myślę, że też nie możemy tego zostawiać na ostatni tydzień, bo te rekordy musimy mieć już przed kręceniem filmiku.

Ogólnie pomysł spoko, no i z formularza się to wygodnie dodaje, także gites 😎 Baza może zostać ta, co jest, w końcu też mamy do niej passy, a szkoda zmieniać (w końcu już są te po 3 rekordy wszędzie 😆)

**Comment by bartlomiej-szlachta** [comment]
Przynależności dodane
