### ISSUE TITLE
Film multimedialny

### ISSUE THREAD

**Issue by kamil-rusin** [Samograje/co-gdzie-kiedy#149]
Klient wymaga filmu jako dokumentacji działającego projektu, w tym elementu *wow*. 
Pomysły?

**Comment by kamil-blonski** [comment]
![image](https://user-images.githubusercontent.com/33577175/72671626-7b13a800-3a4d-11ea-960f-34c9ef080adf.png)

**Comment by bartlomiej-szlachta** [comment]
Myślę, że wystarczy nagrywanie ekranu + dźwięku z mikrofonu.
Byłbym też wdzięczny, gdybyście Wy to ogarnęli.
