### ISSUE TITLE
Rozbudowa mechanizmu filtrowania

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#161]
- ignorowanie rozmiaru liter
- umożliwienie filtrowania podając znak `/` w tekście
- refaktoryzacja - nietworzenie nowego obiektu bazodanowego w kontrolerze

**Comment by kamil-blonski** [comment]
Jak sie wpisze znak `\` to pojawia się exception związany ze złą ścieżką
