### ISSUE TITLE
Implementacja okienek decyzyjnych

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/co-gdzie-kiedy#169]
Okienko powinno być przed próbą usunięcie (tak jak już u mnie) i w momencie kiedy klikniemy "wróć" podczas dodawania/edycji.

**Comment by bartlomiej-szlachta** [comment]
Okienko przy usuwaniu ekranów zaimplementujmy od razu, natomiast implementację go przy anulowaniu zmian w formularzu zostawmy sobie na egzamin. (@kamil25963, u Ciebie chyba to nie jest zaimplementowane przy anulowaniu formularza, no nie?)

**Comment by kamil-blonski** [comment]
Nie jest
