### ISSUE TITLE
Błąd przy edycji sprzętu / Filtrowanie

### ISSUE THREAD

**Issue by kamil-rusin** [Samograje/co-gdzie-kiedy#174]
Błąd zapewne spowodowany niepoprawną aktualizacją wpisów do pickera. 
![image](https://user-images.githubusercontent.com/48494453/72689263-f3db3880-3b0f-11ea-853a-a6366af4c846.png)

**Comment by kamil-rusin** [comment]
Problem jest w obu wersjach - tutaj widać, że problem z filtrem.
![image](https://user-images.githubusercontent.com/48494453/72762471-f9a04f00-3bdf-11ea-83e0-1d09f5e756e6.png)

**Comment by kamil-rusin** [comment]
Przy Zestawie jak wpisujemy poprawne to jest jak należy, ale jak wpiszemy niepoprawnie to wyskakuje to i nie da się tego zmienić.
![image](https://user-images.githubusercontent.com/48494453/72762496-13da2d00-3be0-11ea-8c0c-c2e9866dcd6c.png)

**Comment by kamil-rusin** [comment]
Natomiast w ogóle nie wyświetlają się przynależności. Problem z labelem zapewne.
![image](https://user-images.githubusercontent.com/48494453/72762536-3ff5ae00-3be0-11ea-8bfa-e7f7395f7ee4.png)

**Comment by bartlomiej-szlachta** [comment]
To może pomóc przy błędzie edycji hardware:
![image](https://user-images.githubusercontent.com/37980016/72833388-0af06680-3c87-11ea-8b27-1c451aa94a07.png)

A co do listy przynależności, to moja sprawka, zajmę się tym
