### ISSUE TITLE
Wstępny schemat bazy danych

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#2]
Trzeba zaprojektować schemat bazy danych, jak na przedmiocie z baz danych w poprzednim semestrze. Od razu można wykonać te tabelki z wszystkimi polami, nie trzeba się pierniczyć z tymi grafami z elipsami i rombami. Konwencja nazewnictwa angielska.

Schemat w postaci graficznej (plik jakiegoś programu + screenshot) umieścmy w katalogu `db/schema`. Edytowalny plik jest konieczny z racji tego, że struktura bazy danych będzie się pewnie często zmieniać.

To na tyle mała zmiana w plikach, że można commitować bezpośrednio na gałąź `master`.

**Comment by oliwiabrozek** [comment]
https://www.mysql.com/products/workbench/

Ja używałam tego, jest nawet spoko, chyba że wolicie coś w przeglądarce 😉

**Comment by bartlomiej-szlachta** [comment]
Jak dla mnie bomba, ma nawet opcję generowania SQLi na podstawie diagramu 😎

**Comment by kamil-rusin** [comment]
Też polecam! Używałem na bazach :D
