### ISSUE TITLE
Drobne poprawki bazy danych

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#23]
Trzeba ustawić `hardware.hardware_dictionary_id` jako `not null`

Oczywiście wszystko należy wykonać w modelu w Javie, a uruchomienie aplikacji zaktualizuje nam bazę danych. Trzeba będzie też zaktualizować schemat w `docs/schemat-bazy`.

**Comment by oliwiabrozek** [comment]
dictionary bym akurat zostawiła, bo typ jest wartością w słowniku :)
