### ISSUE TITLE
Skrypt tworzący bazę danych

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#3]
Zadanie na wtedy, gdy będzie gotowy schemat bazy danych (#2).

Baza danych będzie na serwerze, jednak tak czy siak przyda się nam skrypt tworzący ją od zera - to na wypadek, gdyby baza danych nagle padła (lub ktoś zrobił dropa :flushed:) i potrzebowalibyśmy ją odtworzyć od zera. Struktura bazy danych powinna odpowiadać schematowi.

Plik `create.sql` powinien się znaleźć w `db/struktura`.

Do wykonania na osobnej gałęzi, nazwa dowolna, ale po angielsku :stuck_out_tongue_winking_eye:

**Comment by oliwiabrozek** [comment]
Jeśli używalibyśmy Spring Boota to w sumie nie byłoby tego problemu, bo w pliku konfiguracyjnym można wpisać czy Spring ma robić create czy update.

**Comment by bartlomiej-szlachta** [comment]
Racja, można wygenerować skrypt na podstawie encji z modelu w Javie, ale można też zarówno skrypt, jak i model wygenerować ze schematu, co dla mnie wydaje się jeszcze bardziej atrakcyjną opcją 😎 Musimy to przegadać
