### ISSUE TITLE
Dodawanie, edycja i usuwanie hardware'u

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#32]
Analogicznie jak przy przynależnościach, potrzebna jest obsługa dodawania, edycji i usuwania. Klasa `HardwareInputDTO` niech zawiera takie pola jak: `name` (`@NotEmpty`), `dictionaryId` (`@NotNull`), `computerSetId`, `affiliationId` (do uzgodnienia). Od razu też napiszmy wszystkie testy dotyczące tego kontrolera.

**Comment by kamil-rusin** [comment]
Jak robimy z softwareIds? Każdy sprzęt ma jedną licencję, czy jakoś ma mieć historię, że kiedyś miał takie a takie oprogramowanie a teraz ma inne? Tablica Longów? Czy jak xD

**Comment by bartlomiej-szlachta** [comment]
Jednak nie będziemy przypisywać hardware'ori oprogramowania, zaraz usunę to z treści zadania 😉

**Comment by bartlomiej-szlachta** [comment]
Z usuwaniem trzeba poczekać na #40.

**Comment by bartlomiej-szlachta** [comment]
Co do edycji - przyjmijmy, że użytkownik musi podać pełny komplet nowych danych - tych samych, co przy dodawaniu.
