### ISSUE TITLE
Dodawanie, edycja i usuwanie oprogramowania

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#33]
Analogicznie jak przy przynależnościach, potrzebna jest obsługa dodawania, edycji i usuwania. Klasa `SoftwareInputDTO` niech zawiera takie pola jak: `name` (`@NotEmpty`), `computerSetIds`. Od razu też napiszmy wszystkie testy dotyczące tego kontrolera.

Mogą być problemy z uzyskaniem połączenia między oprogramowaniem a przynależnościami czy zestawami komputerowymi, w razie czego siądziemy nad tym wszyscy razem.

**Comment by kamil-blonski** [comment]
Właśnie w tej chwili też patrzałem na schemat i też zauważyłem, że mogą się później pojawić problemy z powiązaniem oprogramowania z zestawem komputerowym (oprogramowanie <->przynależność chyba nie ma sensu). Jeśli chodzi o dodawanie/usuwanie/edycję dla samego pola name, wszystko jest zaimplementowane (sprawdzane z lokalną bazą w postmanie).

Teraz mam pytanie o pole computerSetId. O ile dobrze rozumuje, to żeby przypisać oprogramowanie do zestawu komputerowego (computer_sets) to najpierw musiałbym je przypisać z jakimś sprzętem, podzespołem (hardware), później ten podzespół jest powiązany z zestawem komputerowym. No ale do jakiego sprzętu (hardware) ja to mam przypisać? Dysk, Ram? Procesor? Co w sytuacji wymiany komponentu, do którego przypisany jest akurat ten jeden podzespół? Ewentualnym kompromisem mogłaby być obudowa, ale nie wiem czy można przypisać licencje do obudowy. Jeśli coś pomijam i źle rozumiem to mnie proszę nawrócić, jeśli nie to proponuje zamianę **software_hardware**  na **software_computer_sets** i ewentualnie mógłbym spróbować to zrobić. @oliwiabrozek  @kamil-rusin  wysyłam wam powiadomionko XD.

**Comment by bartlomiej-szlachta** [comment]
Sprawa ustalona - nie przypisujemy oprogramowania do przynależności, ale do wielu zestawów komputerowych. Treść zaktualizowana

**Comment by bartlomiej-szlachta** [comment]
Z usuwaniem trzeba poczekać na #40.

**Comment by bartlomiej-szlachta** [comment]
Co do edycji - przyjmijmy, że użytkownik musi podać pełny komplet nowych danych - tych samych, co przy dodawaniu.
