### ISSUE TITLE
Uzyskanie kodu projektów testowych

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#5]
Jako że musimy się trzymać schematu dokumentacji pracy w projekcie (plik z wymaganiami umieściłem w katalogu `docs`), to do pierwszego kroku potrzebujemy 'kod projektów testowych'. Domyślam się, że mamy przeanalizować dostępne rozwiązania technologiczne i na podstawie ich kodów źródłowych zdecydować o wyborze odpowiedniej technologii. Dlatego proponuję, żeby każdy znalazł jakiś taki projekt do wybranej technologii i umieścił linki do ich kodów źródłowych w komentarzu do tego Issue. Wybierajcie z poniższej listy, co byście chcieli znaleźć, w razie jakichś pomysłów modyfikujcie tą listę. Jak będziemy mieć gotowe, to się spotkamy i wspólnie pooglądamy co mamy i wybierzemy co najlepsze.

Dostępne technologie (nie musimy analizować wszystkich):
- database:
  - MySQL
  - SQLite
- backend:
  - .NET @oliwiabrozek 
  - node.js
  - Java @oliwiabrozek 
  - php & laravel
- frontend:
  - React.js (@bartlomiej-szlachta)
  - Tradycyjny JS (@bartlomiej-szlachta)
- aplikacja mobilna:
  - technologia do przekształcania strony internetowej w apkę mobilną (@kamil-rusin)
  - ten język, w którym będziemy pisać na zajęciach... jak on się nazywał?  (Kotlin :smile:)

**Comment by kamil-rusin** [comment]
- aplikacja mobilna:
Znalazłem artykuł, który pokazuje jak zmienić appki webowe na mobilne. Jeżeli mamy tworzyć w React'ie to polecają ReactNative. Podobno szybko idzie konwertować. 
https://hackernoon.com/web-apps-turn-website-into-mobile-app-your-four-best-options-78fcb2277be8 
W React'ie przykładowa apka - konwerter walut:
https://github.com/BrianLusina/moneta

Istnieją konwertery, ale to nie jest raczej nasz cel 😄 
https://stormotion.io/blog/how-to-turn-a-website-into-an-app/

**Comment by bartlomiej-szlachta** [comment]
Wyręczyłeś mnie z przykładową apką w React xD
Spytałem się w pracy - tam apka w React jest wyświetlana w aplikacji dzięki 'komponentowi WebView na Androidzie'. Dobrze wiedzieć, że jest taka opcja w razie czego, a co do ReactNative... Poczytam o nim, może by to była fajna opcja.
