### ISSUE TITLE
Uzyskiwanie informacji o pojedynczym zestawie komputerowym

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#51]
Ekran edycji zestawu komputerowego będzie się znajdować pod osobną ścieżką w przeglądarce, zatem użytkownik będzie mógł przejść do tego ekranu po prostu wklejając link. W tym momencie trzeba będzie załadować na ekran obecne dane o wybranym zestawie komputerowym, aby umożliwić jego edycję.

Przyda się do tego nowy endpoint. Zapytanie metodą `GET` na adres `/api/computer-sets/{id}` powinno zwrócić JSONa odpowiadającego obiektowi `ComputerSetOutputDTO`.

Od razu napiszmy do tego testy.

**Comment by bartlomiej-szlachta** [comment]
Aktualizacja: Potrzeba jest tutaj inna klasa DTO, ponieważ zamiast nazw obiektów powiązanych, będziemy tutaj potrzebować ich IDki. Myślę, że można by wykorzystać tutaj już istniejącą klasę `ComputerSetInputDTO`, oczywiście trzeba by jej jakoś zmienić nazwę, np na `ComputerSetDTO`.

**Comment by bartlomiej-szlachta** [comment]
Lista zestawów komputerowych powinna zwracać obiekty `ComputerSetListOutputDTO`, zawierające nazwę powiązanej afiliacji oraz numery inwentarzowe powiązanych hardware'u i software'u (a nie obiekty `ComputerSetDTO`)

**Comment by oliwiabrozek** [comment]
Dzięki że rozpisales 🙃
