### ISSUE TITLE
Lista wszystkich hardware'ów

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#58]
Jako że szkoda wywalać metody na listę solo hardware'ów, możemy zrobić tak, że będzie jeden endpoint na obie listy: wszystkich hardware'ów i solo hardware'ów. Wtedy komunikacja odbywałaby się w taki sposób:
- zapytanie metodą `GET` na url: `/api/hardware` zwróciłoby listę wszystkich hardware'ów
- zapytanie metodą `GET` na url: `/api/hardware?solo-only=true` zwróciłoby listę solo hardware'ów

Część urla po pytajniku to tzw parametry zapytania. W kontrolerze można je łatwo wychwycić, dodając do argumentów metody następujący argument:
```
@RequestParam(name = "solo-only", required = false, defaultValue = "false") boolean soloOnly
```

W tym przypadku trzeba też dopisać nowe testy oraz zmodyfikować istniejące.

W komentarzach dodałem kolejne rzeczy xD

**Comment by bartlomiej-szlachta** [comment]
Przy okazji zmieńmy nazwę klasy DTO na taką sugerującą, że output dotyczy listy hardware'u, a nie pojedyńczego hardware'u - np. `HardwareListOutputDTO`.

**Comment by bartlomiej-szlachta** [comment]
Jeszcze jedno - rozszerzmy tą klasę DTO o następujące pola:
- `String inventoryNumber`
- `String affiliationName`
- `String computerSetInventoryNumber`

`affiliationName` to pełna nazwa afiliacji, czyli imię + nazwisko + lokalizacja. Logika sklejająca parametry afiliacji w nazwę jest zawarta w liście afiliacji, trzeba ją wyeksportować do osobnej metody, abyś też mógł z niej skorzystać.

Pozostałe to numery inwentarzowe: hardware'u i computer setu, których jeszcze nie ma w bazie danych. Także trzeba będzie rozbudować model oraz ponownie wygenerować schemat bazy, korzystając z DBeavera. Dodatkowo, w dodawaniu hardware'u trzeba zainicjować parametr `inventoryNumber` w obiekcie. Natomiast chyba nie powinno być opcji edycji numeru inwentarzowego, no nie? Jeśli dobrze myślę, to serwis powinien rzucić `BadRequestException` (dodam go do naszych wyjątków za niedługo), gdy numer inwentarzowy zostanie podany przy edycji.

Zainicjujmy te pola odpowiednio w obu wersjach listy. To też wymaga aktualizacji testów.

**Comment by bartlomiej-szlachta** [comment]
Zaktualizowałem powyższy komentarz

**Comment by bartlomiej-szlachta** [comment]
I zrobiłem to jeszcze raz XD kurczę, kapke się tego nazbierało, więc w razie czego można to rozdzielić na dwa pull requesty

**Comment by kamil-rusin** [comment]
> Natomiast chyba nie powinno być opcji edycji numeru inwentarzowego, no nie? Jeśli dobrze myślę, to serwis powinien rzucić `BadRequestException` (dodam go do naszych wyjątków za niedługo), gdy numer inwentarzowy zostanie podany przy edycji.
> 
Zgadzam się :D Nie powinno być, bo to narusza historię danego sprzętu. To jest unikatowy numer w całym programie - tak jak mówił Klient xD

**Comment by bartlomiej-szlachta** [comment]
Klasa `HardwareDTO` niech posiada pole `inventoryNumber`, bo potrzebne jest do uzyskiwania informacji o pojedynczym hardware. Za to przy dodawaniu i edycji wymuśmy na użytkowniku, żeby zostawił to pole nietknięte - gdy nie będzie nullem, rzućmy `BadRequestException`.

**Comment by kamil-rusin** [comment]
@bartlomiej-szlachta chyba zrobione. Zostało mi dopisać parę testów. Jakbyś mógł spojrzeć na commity na masterze XD plus ComputerSety muszą dodać obsługę inventoryNumber.
