### ISSUE TITLE
Obsługa aparatu na komórze

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#78]
1. W pewnym miejscu na ekranie trzeba dodać przycisk, który będzie widoczny tylko w aplikacji mobilnej
2. Przycisk ten niech otwiera aparat urządzenia.

Póki co tylko tyle, albo aż tyle 😄

**Comment by kamil-rusin** [comment]
https://github.com/react-native-community/react-native-camera

**Comment by kamil-rusin** [comment]
https://react-native-community.github.io/react-native-camera/docs/installation

**Comment by kamil-rusin** [comment]
https://github.com/moaazsidat/react-native-qrcode-scanner
Tutaj od razu jest kamera ze skanerem. Kwestia tego, że albo użyjemy Modal albo osobny ekran - pytanie jak wtedy wrócić do ekranu z listą z filtrem ustawionym na numer seryjny?

**Comment by kamil-rusin** [comment]
https://www.youtube.com/watch?v=jTm4fjx_eZ0

**Comment by kamil-rusin** [comment]
https://facebook.github.io/react-native/docs/modal
