### ISSUE TITLE
Błąd przy pobieraniu listy hardware'u

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#90]
Zapytanie metodą `GET` na adres `/api/hardware` powoduje `Internal Server Error`, zamiast zwrócić listę wszystkich hardware'ów.

![image](https://user-images.githubusercontent.com/37980016/70549826-24c16880-1b75-11ea-9120-d82dc7546b76.png)

**Comment by kamil-rusin** [comment]
Co w takim wypadku mam zrobić? Wczoraj pokazywałem ścieżkę z argumentem.

**Comment by bartlomiej-szlachta** [comment]
Działa, zamykamy
