### ISSUE TITLE
Zmiana motywu kolorystycznego aplikacji

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/co-gdzie-kiedy#98]
Można zmienić kolor oraz ikonki aplikacji. Miejsca, w których trzeba dokonać zmiany, to:
- ikony aplikacji Androida (łącznie 10 ikon) w katalogu `frontend/android/app/src/main/res`
- ikona aplikacji w przeglądarce - `frontend/public/favicon.ico`
- kolor górnego paska w mobilnej przeglądarce Chrome - `frontend/public/index.html`
- kolory w innych miejscach aplikacji - `frontend/src/constValues.js`

Możliwe, że jeszcze o czymś zapomniałem, także w razie czego by trzeba było zmienić coś jeszcze

**Comment by oliwiabrozek** [comment]
😍
